version: "3.6"
services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    networks:
      - default
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${USERDIR}/docker/portainer/data:/data
      - ${USERDIR}/docker/shared:/shared
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
  homeassistant:
    image: homeassistant/home-assistant
    container_name: homeassistant
    restart: unless-stopped
    volumes:
      - ${USERDIR}/docker/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/shared:/shared
      - ${USERDIR}/docker/nodered/data/etc/camera-images:/config/www/camera-images
    network_mode: host
    ports:
      - "8123:8123"
      - "56700:56700/udp"
    privileged: true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
  mosquitto:
    image: eclipse-mosquitto
    container_name: mqtt
    restart: unless-stopped
    volumes:
      - ${USERDIR}/docker/mosquitto/config:/mosquitto/config
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/mosquitto/data/mosquitto-data:/mosquitto/data
      - ${USERDIR}/docker/mosquitto/data/mosquitto-log:/mosquitto/log
    network_mode: host
    ports:
      - "1883:1883"
      - "9001:9001"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
  unifi:
    image: jacobalberty/unifi:arm32v7
    container_name: unifi
    restart: always
    network_mode: host
    volumes:
      - ${USERDIR}/docker/unifi/data/lib:/unifi/data
      - ${USERDIR}/docker/unifi/data/log:/unifi/log
      - ${USERDIR}/docker/unifi/data/run:/var/run/unifi
    ports:
      - "3478:3478/udp"
      - "10001:10001/udp"
      - "6789:6789/tcp"
      - "8080:8080/tcp"
      - "8081:8081/tcp"
      - "8880:8880/tcp"
      - "8443:8443/tcp"
      - "8843:8843/tcp"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UNIFI_HTTP_PORT=8080
      - UNIFI_HTTPS_PORT=8443
  pihole:
    image: pihole/pihole
    container_name: pihole
    restart: unless-stopped
    ports:
      - "192.168.1.42:53:53/tcp"
      - "192.168.1.42:53:53/udp"
      - "192.168.1.42:67:67/udp"
      - "192.168.1.42:8181:80/tcp"
      - "192.168.1.42:8444:443/tcp"
    environment:
      - TZ=${TZ}
    volumes:
       - ${USERDIR}/docker/pihole/etc:/etc/pihole/
       - ${USERDIR}/docker/pihole/dnsmasq:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    networks:
      - default
  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    restart: unless-stopped
    depends_on:
      - mosquitto
      - homeassistant
    networks:
      - default
    ports:
      - "1880:1880"
    volumes:
      - ${USERDIR}/docker/nodered/data/etc:/data
    environment:
      - user=${PUID}
      - TZ=${TZ}
networks:
  default:
    driver: bridge